### ISSUE TITLE
1.5.2 breaks API (maybe 1.5.1 too)

### ISSUE THREAD

**Issue by lcoderre** [rt2zz/redux-persist#56]
EDIT: found the problem.

My package.json uses ^1.5.0, and downloads 1.5.2, which breaks changes.

---
Hello, 
I am having a problem with redux-persist, but I believe it has something to do with my environment, not specifically this package. However since the error clearly happens during the use of this package, I thought you might have a hint to solve my problem!

Here is the issue: https://stackoverflow.com/questions/35296078/localstorage-suddenly-broken

Thanks.

**Comment by rt2zz** [comment]
Ah, this was not a breaking change, but rather a bug. 

I just pushed 1.5.3, but I will need to do further testing to confirm all potentially related issues are resolved.

**Comment by technicallyjosh** [comment]
I can confirm that 1.5.3 fixes the `storage.getItem is not a function` issue. Things in my app seem to be back to normal.

**Comment by rt2zz** [comment]
@lcoderre @technicallyjosh thanks for reporting & testing!

I am working on a 2.0 which will make things a little simpler, and time permitting have actual browser tests not just mocha tests.
