### ISSUE TITLE
Error saying redux persist.autorehydrate is not a function

### ISSUE THREAD

**Issue by dhanala89** [rt2zz/redux-persist#547]
// add the autoRehydrate enhancer
  if (ReduxPersist.active) {
    enhancers.push(autoRehydrate())
  }

autoRehydrate() is error-ing out when upgraded to v5.2.2. Any ideas? Has the autoRehyderate function been replaced by something else?

**Comment by rt2zz** [comment]
ya, check the readme for v5 upgrade instructions, or otherwise feel free to stick on v4 it works well for most use cases

**Comment by dhanala89** [comment]
thanks rt2zz but those instructions just says remove autoRehydrate and nothing mentioned about what would autoRehydrate replace?

**Comment by rt2zz** [comment]
you replace it with persistReducer, but its not 1-1

**Comment by allenmanning** [comment]
I just hit this too.  I'm not debating if I should stick with V4, which makes me wonder what the future is with this project.  Maybe you should consider making a new project if you only have an experimental migration path.  This may be good food for thought on breaking changes such as this:
https://www.youtube.com/watch?v=oyLBGkS5ICk

**Comment by rt2zz** [comment]
not interested in maintaining two modules that do the same basic thing. The data migration path is only experimental because it has not been tested, but please by all means do test it, if we get several reports of it working we will drop the "experimental" bit.

There is also nothing wrong with sticking to v4, thats the benefit of semver!

**Comment by allenmanning** [comment]
Fair enough, thanks for the response.  It is a cool project thanks for maintaining it.

**Comment by corysimmons** [comment]
@rt2zz Agree with not maintaining multiple APIs/etc. But it would be nice to have some official upgrade docs (on the repo Wiki?) from v4 to v5.

Thanks for your hard work!

**Comment by rt2zz** [comment]
ah I recently removed this from the readme thinking it had been long enough. migration guide still lives here: https://github.com/rt2zz/redux-persist/blob/master/docs/MigrationGuide-v5.md

We should probably add a link back to the readme.

**Comment by corysimmons** [comment]
It's up to you. tbh I wrote that before I even tried to implement (just as a "good housekeeping" kinda chore), but when I actually implemented it couldn't have been easier.

The only bit of docs I think could use work is with https://github.com/wix/react-native-navigation

I found the GH Issue and the SO comment, but still had to do some tinkering to get it to work right. Clean docs on that would be great.

**Comment by brunolemos** [comment]
> you replace it with persistReducer, but its not 1-1

@rt2zz where can I read about the differences?
Just migrated from v4 to v5, had some difficulties but seems to be working fine. Not sure what autoRehydrate has that v5 doesn't have

**Comment by sibelius** [comment]
@rt2zz you can close this

follow migration guide https://github.com/rt2zz/redux-persist/blob/master/docs/MigrationGuide-v5.md
